// Hive Types
const int HIVE_TYPE_ID_USER_VO = 1;
const int HIVE_TYPE_ID_CARD_VO = 2;
const int HIVE_TYPE_ID_REGISTER_AND_LOGIN_VO = 3;
const int HIVE_TYPE_ID_MOVIE_VO = 4;
const int HIVE_TYPE_ID_CAST_VO = 5;
const int HIVE_TYPE_ID_CINEMA_VO = 6;
const int HIVE_TYPE_ID_SNACK = 7;
const int HIVE_TYPE_ID_TIMESLOT = 8;

// Box Names
const String BOX_NAME_USERINFO_VO = "BOX_NAME_USERINFO_VO";
const String BOX_NAME_TOKEN_VO = "BOX_NAME_TOKEN";
const String BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const String BOX_NAME_CAST_VO = "BOX_NAME_CAST_VO";
const String BOX_NAME_CINEMA_VO = "BOX_NAME_CINEMA_VO";
const String BOX_NAME_SNACK_VO = "BOX_NAME_SNACK_VO";
const String BOX_NAME_TIMESLOT_VO = "BOX_NAME_TIMESLOT_VO";